[package]
name = "adt"
description = "Reader for Blizzard's WDT and ADT terrain formats, as used by WoW 3.3.5a."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chunk = { path = "../chunk" }
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
dbc = { path = "../dbc" }
m2 = { path = "../m2" }
mpq = { path = "../mpq" }
