[package]
name = "wow-cli"
description = "Inspection tool for WoW 3.3.5a client data."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
mpq = { path = "../../crates/mpq" }
dbc = { path = "../../crates/dbc" }
blp = { path = "../../crates/blp" }
png.workspace = true
anyhow.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
m2 = { version = "0.0.1", path = "../../crates/m2" }
wmo = { version = "0.0.1", path = "../../crates/wmo" }
adt = { version = "0.0.1", path = "../../crates/adt" }
auth = { version = "0.0.1", path = "../../crates/auth" }
