[package]
name = "wow-viewer"
description = "Windowed asset viewer for WoW 3.3.5a client data."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
mpq = { path = "../../crates/mpq" }
blp = { path = "../../crates/blp" }
render = { path = "../../crates/render" }

wgpu.workspace = true
winit.workspace = true
egui.workspace = true
egui-wgpu.workspace = true
egui-winit.workspace = true
pollster.workspace = true
png.workspace = true
anyhow.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
m2 = { version = "0.0.1", path = "../../crates/m2" }
dbc = { version = "0.0.1", path = "../../crates/dbc" }
glam.workspace = true
wmo = { version = "0.0.1", path = "../../crates/wmo" }
adt = { version = "0.0.1", path = "../../crates/adt" }
